"""Deleted department class

Revision ID: 6521428aa907
Revises: 8c24f6c8a99f
Create Date: 2024-03-23 22:10:21.081292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6521428aa907'
down_revision: Union[str, None] = '8c24f6c8a99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.VARCHAR(), nullable=True),
    sa.Column('managers_name', sa.VARCHAR(), nullable=True),
    sa.Column('staffs', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
