"""Adding one to many relationship between Doctor and Patient

Revision ID: 8c24f6c8a99f
Revises: 90214a7ba516
Create Date: 2024-03-21 17:06:54.739742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c24f6c8a99f'
down_revision: Union[str, None] = '90214a7ba516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
